services:
    cluemp:
        build:
            context: .
        container_name: cluemp
        restart: unless-stopped
        environment:
            NODE_ENV: production
            HOST: 0.0.0.0
            PORT: 8000
            ALLOWED_ORIGINS: https://cluemp.duckdns.org
        expose:
            - "3000"
            - "8000"
        networks:
            - web

networks:
    web:
        external: true
